# ============================================================
# Credit Risk Example: Expected Loss and Simulation
# ============================================================
#
# Goal:
# We have 10 firms. Each firm borrows 100,000 euros from a bank.
# They either:
#   - do NOT default  -> repay everything -> bank loss = 0
#   - default         -> repay only 50,000 -> bank loss = 50,000
#
# Default probabilities are:
# Firm 1: 1%
# Firm 2: 2%
# ...
# Firm 10: 10%
#
# We will do this step by step so that students can see:
# 1. how a Bernoulli random variable works,
# 2. how firm-level losses are generated,
# 3. how one portfolio loss is obtained,
# 4. how repeating this many times creates a loss distribution.
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Set the parameters of the problem
# ------------------------------------------------------------

# Fixing the random seed means that the random draws will be reproducible.
# This is useful for teaching, debugging, and comparing results.
np.random.seed(42)

# First, recall how NumPy is imported:
# import numpy as np
#
# Here, 'np' is just a short name (alias) for the NumPy library.
#
# Understanding the "dot" (.)
# The dot is used to access something *inside* an object.
#
# General idea:
# object.attribute_or_function
#
# In this case:
# np.random.seed
#
# means:
# - np        → the NumPy library
# - random    → a module inside NumPy (for random numbers)
# - seed      → a function inside the random module

# So we are navigating step by step:
# NumPy → random module → seed function

# ----------------------------------------
# What does seed(42) do?
# ----------------------------------------
# Random numbers in Python are not truly random.
# They are generated by a deterministic algorithm.
#
# The "seed" is the starting point of that algorithm.
# means:
# → "Start the random number generator from a fixed point (42)"
#
# As a result:
# → Every time you run the code, you get the SAME random numbers

# ----------------------------------------
# Why is this important?
# ----------------------------------------
# a. Reproducibility:
#    Students, researchers, or collaborators get the same results
#
# b. Debugging:
#    You can reproduce exactly the same "random" outcome
#


# Number of firms in the portfolio
n_firms = 10

# Exposure of each firm (loan amount)
loan_amount = 100000

# Amount repaid if a firm defaults
recovery_amount = 50000

# Therefore, the bank's loss if a firm defaults is:
loss_if_default = loan_amount - recovery_amount  # = 50,000

# Default probabilities for the 10 firms:
# 0.01, 0.02, ..., 0.10
default_probabilities = np.arange(1, 11) / 100

# Create default probabilities for 10 firms: 1%, 2%, ..., 10%

# np.arange(1, 11) generates the integers from 1 up to (but not including) 11:
# → array([1, 2, 3, ..., 10])

# Dividing by 100 applies element-wise:
# → each number is converted into a probability (percentage form)
# → array([0.01, 0.02, 0.03, ..., 0.10])

# So overall, this line creates:
# p_i = i / 100 for i = 1,...,10

# Firm names, just for readability
firm_names = [f"Firm_{i}" for i in range(1, n_firms + 1)]

# Create a list of firm names: "Firm_1", "Firm_2", ..., "Firm_10"

# This is a "list comprehension", which is a compact way to build a list.

# range(1, n_firms + 1) generates numbers:
# → 1, 2, 3, ..., n_firms
# (the +1 is needed because Python excludes the upper bound)

# For each number i, we create a string using an f-string:
# f"Firm_{i}" means:
# → take the value of i and insert it into the string
# Example: if i = 3 → "Firm_3"

# So overall, this line means:
# → for each i from 1 to n_firms, create "Firm_i"
# → collect all of them into a list


print("Default probabilities:")
for firm, p in zip(firm_names, default_probabilities):
    # f-string formatting:
    # {firm} → inserts the firm name
    # {p:.0%} → formats the number as a percentage with 0 decimal places
    # Example: 0.01 → "1%"
    print(f"{firm}: {p:.0%}")

# Loop over firm names and their corresponding default probabilities

# zip(firm_names, default_probabilities) combines two lists element by element:
# It creates pairs like:
# ("Firm_1", 0.01), ("Firm_2", 0.02), ..., ("Firm_10", 0.10)

# So in each iteration of the loop:
# - 'firm' takes the name (e.g., "Firm_1")
# - 'p' takes the corresponding probability (e.g., 0.01)

# This allows us to iterate over both lists at the same time in a clean way


# ------------------------------------------------------------
# 2. Compute the expected loss analytically
# ------------------------------------------------------------
#
# For one firm:
#   Expected Loss = P(default) × Loss if default
#
# For the whole portfolio:
#   Total Expected Loss = sum over all firms of:
#                         p_i × loss_if_default
#
# This is NOT simulation yet.
# This is the theoretical average loss.
# ------------------------------------------------------------

expected_loss_per_firm = default_probabilities * loss_if_default
total_expected_loss = expected_loss_per_firm.sum()

# expected_loss_per_firm is a NumPy array:
# → it contains the expected loss for each firm
# → e.g. array([500, 1000, ..., 5000])

# In NumPy, arrays are objects that come with built-in functions (called "methods")

# One of these methods is .sum()
# → it adds up all elements in the array

# The dot (.) means:
# → "use a function that belongs to this object"

# So:
# expected_loss_per_firm.sum()
# means:
# → take this array and compute the sum of all its elements

# This gives the total expected loss of the portfolio

# total_expected_loss = expected_loss_per_firm.sum()

# ------------------------------------------------------------
# Understanding this line using NumPy, classes, and methods
# ------------------------------------------------------------

# In NumPy, expected_loss_per_firm is NOT just a simple list.
# It is an object of a specific type (a "class"):
# → numpy.ndarray

# You can check this with:
print(type(expected_loss_per_firm))
# → <class 'numpy.ndarray'>

# ------------------------------------------------------------
# What is a "class"?
# ------------------------------------------------------------
# A class is like a blueprint for creating objects.
#
# Example:
# - The class: numpy.ndarray
# - The object: expected_loss_per_firm
#
# The object contains:
# 1) Data   (the numbers inside the array)
# 2) Methods (functions that operate on this data)

# ------------------------------------------------------------
# What is a "method"?
# ------------------------------------------------------------
# A method is a function that belongs to an object (or class).
#
# You call a method using the dot (.)
# → object.method()

# Example:
expected_loss_per_firm.sum()

# This means:
# → "use the sum method that belongs to this NumPy array"

# ------------------------------------------------------------
# What does .sum() do?
# ------------------------------------------------------------
# It adds up all elements in the array.

# So:
# expected_loss_per_firm = array([500, 1000, ..., 5000])
#
# expected_loss_per_firm.sum()
# → returns the total (a single number)

# ------------------------------------------------------------
# Alternative using NumPy function
# ------------------------------------------------------------
# NumPy also provides a standalone function:

np.sum(expected_loss_per_firm)

# Both are equivalent:
# - expected_loss_per_firm.sum()   (method of the array)
# - np.sum(expected_loss_per_firm) (function from NumPy)

# ------------------------------------------------------------
# Key takeaway for students
# ------------------------------------------------------------
# - expected_loss_per_firm is an object (NumPy array)
# - It has built-in methods like .sum(), .mean(), etc.
# - The dot (.) is used to access these methods
# - This is part of object-oriented programming in Python
#
# Simple intuition:
# → "Ask the array to compute its own sum"

print("\nExpected loss per firm:")
for firm, el in zip(firm_names, expected_loss_per_firm):
    print(f"{firm}: €{el:,.2f}")

print(f"\nTotal expected loss of the portfolio: €{total_expected_loss:,.2f}")


# ------------------------------------------------------------
# 3. Step 1 of simulation:
#    Simulate default / no default for the 10 firms ONCE
# ------------------------------------------------------------
#
# A default indicator is a Bernoulli random variable:
#   Y_i = 1 if firm i defaults
#   Y_i = 0 otherwise
#
# np.random.binomial(n=1, p=p_i) gives exactly this:
#   - 1 with probability p_i
#   - 0 with probability 1-p_i
# ------------------------------------------------------------

one_draw_defaults = np.random.binomial(n=1, p=default_probabilities)

# ------------------------------------------------------------
# What does this line do?
# ------------------------------------------------------------
# It simulates whether each firm defaults or not.
#
# The result will be an array of 0s and 1s:
# → 1 = default
# → 0 = no default

# ------------------------------------------------------------
# Breaking it down
# ------------------------------------------------------------

# np.random.binomial(...) is a function from NumPy
# → used to simulate outcomes from a Binomial distribution

# General form:
# np.random.binomial(n, p)

# - n = number of trials
# - p = probability of success

# ------------------------------------------------------------
# Why n = 1?
# ------------------------------------------------------------
# When n = 1, the Binomial distribution becomes a Bernoulli distribution:
#
# → Only one trial
# → Two possible outcomes:
#    1 with probability p   (default)
#    0 with probability 1-p (no default)

# So here:
# Each firm has ONE trial:
# → "Does the firm default or not?"

# ------------------------------------------------------------
# What is p = default_probabilities?
# ------------------------------------------------------------
# default_probabilities is an array:
# → [0.01, 0.02, ..., 0.10]
#
# NumPy applies the function element-wise:
# → each firm gets its own probability

# So internally, this is like doing:
# Firm 1: draw from Bernoulli(0.01)
# Firm 2: draw from Bernoulli(0.02)
# ...
# Firm 10: draw from Bernoulli(0.10)

# ------------------------------------------------------------
# Output
# ------------------------------------------------------------
# The result is an array like:
# → [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
#
# This means:
# → Firm 4 defaulted
# → Firm 9 defaulted
# → others did not

# ------------------------------------------------------------
# Conceptual takeaway
# ------------------------------------------------------------
# - Each firm’s default is a random variable (Bernoulli)
# - This line generates ONE realization of all 10 firms
# - Repeating this many times → gives us a distribution of outcomes

print("\nOne simulation of default indicators for the 10 firms:")
for firm, default in zip(firm_names, one_draw_defaults):
    print(f"{firm}: {default}")


# ------------------------------------------------------------
# 4. Step 2 of simulation:
#    Convert default indicators into firm-level losses
# ------------------------------------------------------------
#
# If default indicator = 1 -> loss = 50,000
# If default indicator = 0 -> loss = 0
#
# This shows how a random variable (default) is mapped into
# another random variable (loss).
# ------------------------------------------------------------

one_draw_losses = one_draw_defaults * loss_if_default

print("\nLosses for the 10 firms in this one simulation:")
for firm, loss in zip(firm_names, one_draw_losses):
    print(f"{firm}: €{loss:,.2f}")


# ------------------------------------------------------------
# 5. Step 3 of simulation:
#    Compute the total portfolio loss for this one simulation
# ------------------------------------------------------------

one_portfolio_loss = one_draw_losses.sum()

print(f"\nTotal portfolio loss in this one simulation: €{one_portfolio_loss:,.2f}")


# ------------------------------------------------------------
# 6. Put this one simulation into a DataFrame
# ------------------------------------------------------------
#
# This makes the result easier to inspect.
# ------------------------------------------------------------

# one_simulation_df = pd.DataFrame({...})

# ------------------------------------------------------------
# What is pd.DataFrame?
# ------------------------------------------------------------
# pandas (imported as pd) provides a data structure called a "DataFrame".
#
# A DataFrame is like a table:
# → rows and columns (similar to Excel or a database table)

# Each column has a name, and contains a sequence of values.

# ------------------------------------------------------------
# Breaking down this code
# ------------------------------------------------------------

one_simulation_df = pd.DataFrame({
    "Firm": firm_names,
    "Default_Probability": default_probabilities,
    "Default_Indicator": one_draw_defaults,
    "Loss_EUR": one_draw_losses
})

# ------------------------------------------------------------
# What does pd.DataFrame({...}) do?
# ------------------------------------------------------------
# We pass a dictionary (key → value pairs) into DataFrame:
#
# {
#   "Column_Name": data,
#   ...
# }

# Each key becomes a column name.
# Each value must be a list/array of the same length.

# So here:
# - "Firm" → ["Firm_1", ..., "Firm_10"]
# - "Default_Probability" → [0.01, ..., 0.10]
# - "Default_Indicator" → [0, 1, 0, ...]
# - "Loss_EUR" → [0, 50000, 0, ...]

# ------------------------------------------------------------
# Resulting structure
# ------------------------------------------------------------
# The DataFrame will look like a table:

#   Firm     Default_Probability   Default_Indicator   Loss_EUR
# ------------------------------------------------------------
# Firm_1            0.01                  0               0
# Firm_2            0.02                  1           50000
# ...
# Firm_10           0.10                  0               0

# Each row corresponds to ONE firm.

# ------------------------------------------------------------
# Important requirement
# ------------------------------------------------------------
# All columns must have the same length:
# → here: 10 entries (one for each firm)

# Otherwise, pandas will raise an error.

# ------------------------------------------------------------
# Why use a DataFrame?
# ------------------------------------------------------------
# - Easy to read (structured like a table)
# - Easy to analyze (filter, group, summarize)
# - Standard tool in data analysis and finance

# ------------------------------------------------------------
# Conceptual takeaway
# ------------------------------------------------------------
# - DataFrame = structured representation of your data
# - Columns = variables (firm, probability, default, loss)
# - Rows = observations (here: firms in one simulation)

print("\nDataFrame for one simulation:")
print(one_simulation_df)


# ------------------------------------------------------------
# 7. Step 4 of simulation:
#    Repeat the same experiment 10 times
# ------------------------------------------------------------
#
# Each row = one simulation of the entire 10-firm portfolio
# Each column = one firm's default indicator in that simulation
#
# This is the next conceptual step:
#   one Bernoulli draw  -> one portfolio outcome
#   repeated outcomes   -> sample of possible portfolio states
# ------------------------------------------------------------

n_sim_10 = 10

# Each row corresponds to one repetition of the whole portfolio experiment
defaults_10_sims = np.random.binomial(
    n=1,
    p=default_probabilities,
    size=(n_sim_10, n_firms)
)

# ------------------------------------------------------------
# Understanding function inputs (arguments) in Python
# ------------------------------------------------------------
# A function is something that takes inputs and returns an output.
#
# General structure:
# function_name(argument1=value1, argument2=value2, ...)
#
# Here:
# np.random.binomial(...) is the function
# n=1, p=..., size=... are the inputs (arguments)

# These are called "keyword arguments":
# → we explicitly name each input (n=..., p=..., size=...)

# ------------------------------------------------------------
# What does this function do?
# ------------------------------------------------------------
# It generates random numbers from a Binomial distribution.

# General meaning:
# np.random.binomial(n, p, size)

# - n     → number of trials
# - p     → probability of success
# - size  → shape of the output (how many draws we want)

# ------------------------------------------------------------
# Input 1: n = 1
# ------------------------------------------------------------
# This means each draw is a Bernoulli random variable:
# → only one trial
# → outcome is either:
#    1 (default) or 0 (no default)

# ------------------------------------------------------------
# Input 2: p = default_probabilities
# ------------------------------------------------------------
# This is an array:
# → [0.01, 0.02, ..., 0.10]
#
# NumPy applies this element-wise:
# → each firm has its own probability

# ------------------------------------------------------------
# Input 3: size = (n_sim_10, n_firms)
# ------------------------------------------------------------
# This controls the SHAPE of the output
#
# (rows, columns) = (number of simulations, number of firms)
#
# For example:
# n_sim_10 = 10
# n_firms  = 10
#
# → output is a 10 × 10 matrix

# ------------------------------------------------------------
# What does the output represent?
# ------------------------------------------------------------
# Each ROW = one simulation (one full portfolio realization)
# Each COLUMN = one firm
#
# Example output:
# [
#  [0, 0, 1, 0, ..., 0],   ← Simulation 1
#  [0, 1, 0, 0, ..., 1],   ← Simulation 2
#  ...
# ]

# So:
# defaults_10_sims[i, j] =
# → default outcome of firm j in simulation i

# ------------------------------------------------------------
# Important concept: vectorization
# ------------------------------------------------------------
# Instead of looping:
# for each simulation:
#     for each firm:
#         draw a Bernoulli random variable
#
# NumPy does everything in ONE function call.
#
# This is:
# → faster
# → cleaner
# → standard in scientific computing

# ------------------------------------------------------------
# Conceptual takeaway
# ------------------------------------------------------------
# - Functions take inputs (arguments) and return outputs
# - Keyword arguments (n=..., p=..., size=...) improve readability
# - size defines the structure of the result
# - This single line generates MANY random variables at once


# Convert defaults into losses
losses_10_sims = defaults_10_sims * loss_if_default

# Total loss per simulation
portfolio_losses_10_sims = losses_10_sims.sum(axis=1)

# Build a DataFrame
df_10_sims = pd.DataFrame(defaults_10_sims, columns=[f"{name}_default" for name in firm_names])

# ------------------------------------------------------------
# Another way to create a DataFrame (not using a dictionary)
# ------------------------------------------------------------
# Previously, we used:
# pd.DataFrame({column_name: data, ...})
#
# Here, we use a different approach:
# → directly pass a 2D array (matrix) as the data

# ------------------------------------------------------------
# Step 1: What is defaults_10_sims?
# ------------------------------------------------------------
# It is a NumPy array with shape:
# (n_sim_10, n_firms)
#
# Example: (10, 10)
#
# That means:
# - 10 rows   → 10 simulations
# - 10 columns → 10 firms

# ------------------------------------------------------------
# Step 2: Passing the array into DataFrame
# ------------------------------------------------------------
# pd.DataFrame(defaults_10_sims)
#
# This tells pandas:
# → "Turn this matrix into a table"
#
# By default:
# - rows are indexed 0,1,2,...
# - columns are named 0,1,2,...

# ------------------------------------------------------------
# Step 3: Naming the columns
# ------------------------------------------------------------
# columns=[f"{name}_default" for name in firm_names]
#
# This creates a list like:
# ["Firm_1_default", "Firm_2_default", ..., "Firm_10_default"]
#
# So each column corresponds to one firm’s default indicator

# ------------------------------------------------------------
# Final result
# ------------------------------------------------------------
# Each row = one simulation
# Each column = default indicator of a firm
#
# Example:
#   Firm_1_default   Firm_2_default   ...   Firm_10_default
# --------------------------------------------------------
#         0                 1                  ...      0
#         0                 0                  ...      1
#         ...
#
# ------------------------------------------------------------
# Key difference vs dictionary approach
# ------------------------------------------------------------
#
# 1. Dictionary approach:
#    pd.DataFrame({
#        "Firm": ...,
#        "Loss": ...
#    })
#    → You define each column explicitly
#
# 2. Array approach (this one):
#    pd.DataFrame(data, columns=...)
#    → You already have structured data (matrix)
#    → You just assign column names
#
# ------------------------------------------------------------
# When to use which?
# ------------------------------------------------------------
# - Use dictionary:
#   when columns come from different sources
#
# - Use array + columns:
#   when your data is already in matrix form (like simulations)
#
# ------------------------------------------------------------
# Conceptual takeaway
# ------------------------------------------------------------
# pandas DataFrame can be created in multiple ways:
# - from a dictionary (column-wise construction)
# - from a NumPy array (matrix-style construction)
#
# This flexibility is very useful in data analysis

# Add firm-level losses as extra columns
for i, name in enumerate(firm_names):
    df_10_sims[f"{name}_loss"] = losses_10_sims[:, i]

# Add total portfolio loss
df_10_sims["Total_Portfolio_Loss"] = portfolio_losses_10_sims

print("\nDataFrame for 10 simulations:")
print(df_10_sims)


# ------------------------------------------------------------
# 8. Step 5 of simulation:
#    Expand from 10 simulations to 1000 simulations
# ------------------------------------------------------------
#
# This is where simulation becomes useful for statistical analysis.
# One simulation shows one possible outcome.
# Many simulations show the distribution of possible outcomes.
# ------------------------------------------------------------

n_sim_1000 = 1000

defaults_1000_sims = np.random.binomial(
    n=1,
    p=default_probabilities,
    size=(n_sim_1000, n_firms)
)

losses_1000_sims = defaults_1000_sims * loss_if_default
portfolio_losses_1000_sims = losses_1000_sims.sum(axis=1)

# ------------------------------------------------------------
# 9. Build a detailed DataFrame for the 1000 simulations
# ------------------------------------------------------------

df_1000_sims = pd.DataFrame(
    defaults_1000_sims,
    columns=[f"{name}_default" for name in firm_names]
)

# Add firm-level losses
for i, name in enumerate(firm_names):
    df_1000_sims[f"{name}_loss"] = losses_1000_sims[:, i]

# Add total loss for each simulation
df_1000_sims["Total_Portfolio_Loss"] = portfolio_losses_1000_sims

print("\nFirst 10 rows of the 1000-simulation DataFrame:")
print(df_1000_sims.head(10))


# ------------------------------------------------------------
# 10. Compare simulated average loss to theoretical expected loss
# ------------------------------------------------------------
#
# The average of many simulated losses should be close to the
# theoretical expected loss.
#
# It will usually not be exactly equal, because simulation is based
# on random draws.
# But with many simulations, it should be reasonably close.
# ------------------------------------------------------------

simulated_average_loss = df_1000_sims["Total_Portfolio_Loss"].mean()

print(f"\nTheoretical expected loss: €{total_expected_loss:,.2f}")
print(f"Simulated average loss (1000 simulations): €{simulated_average_loss:,.2f}")


# ------------------------------------------------------------
# 11. Frequency table of total losses
# ------------------------------------------------------------
#
# Because each default causes a loss of 50,000 euros,
# possible total losses are:
# 0, 50,000, 100,000, 150,000, ...
#
# This table shows how often each loss level appeared.
# ------------------------------------------------------------

loss_frequency = (
    df_1000_sims["Total_Portfolio_Loss"]
    .value_counts()
    .sort_index()
    .reset_index()
)

loss_frequency.columns = ["Total_Portfolio_Loss", "Count"]
loss_frequency["Relative_Frequency"] = loss_frequency["Count"] / n_sim_1000

print("\nFrequency table of total portfolio loss:")
print(loss_frequency)


# ------------------------------------------------------------
# 12. Plot the loss distribution
# ------------------------------------------------------------
#
# Since the total loss can only take discrete values
# (multiples of 50,000), a bar chart is often very intuitive.
# A histogram also works, but a bar chart shows the exact mass
# at each possible loss level more clearly.
# ------------------------------------------------------------

# ------------------------------------------------------------
# Basic grammar of plotting with matplotlib
# ------------------------------------------------------------

# matplotlib.pyplot (imported as plt) is a module used for plotting.
# Think of it as a "toolbox" for creating figures step by step.

# The general structure is:
# 1. Create a figure (the canvas)
# 2. Add a plot (bars, lines, etc.)
# 3. Add labels and formatting
# 4. Display the result

# ------------------------------------------------------------
# Step 1: Create a figure
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

# plt.figure(...) creates a new plotting area (a canvas)
#
# figsize=(10, 6):
# → width = 10 inches, height = 6 inches
# → controls the size of the plot


# ------------------------------------------------------------
# Step 2: Create a bar chart
# ------------------------------------------------------------

plt.bar(
    loss_frequency["Total_Portfolio_Loss"],   # x-axis values
    loss_frequency["Relative_Frequency"],     # y-axis values
    width=35_000
)

# plt.bar(x, y, ...) creates a bar chart
#
# - x: positions of the bars (here: possible loss levels)
# - y: heights of the bars (here: frequencies)
#
# loss_frequency["..."] means:
# → select a column from the DataFrame
#
# width=35_000:
# → controls how wide each bar is on the x-axis
# → here chosen to match the scale of losses (multiples of 50,000)


# ------------------------------------------------------------
# Step 3: Add labels and title
# ------------------------------------------------------------

plt.xlabel("Total Portfolio Loss (EUR)")
# → label for x-axis

plt.ylabel("Relative Frequency")
# → label for y-axis

plt.title("Simulated Loss Distribution of the 10-Firm Portfolio")
# → title of the plot


# ------------------------------------------------------------
# Step 4: Add grid
# ------------------------------------------------------------

plt.grid(axis="y", alpha=0.3)

# Adds grid lines
#
# axis="y":
# → only horizontal lines (helps read frequencies)
#
# alpha=0.3:
# → transparency (0 = invisible, 1 = solid)
# → lower value = lighter grid


# ------------------------------------------------------------
# Step 5: Display the plot
# ------------------------------------------------------------

plt.show()

# This renders (displays) the figure.
# Without this, the plot may not appear (especially in scripts).


# ------------------------------------------------------------
# Conceptual takeaway
# ------------------------------------------------------------
# - plt is a module (like np, pd)
# - You call functions using the dot: plt.function(...)
# - Each line adds something to the same figure
#
# So plotting is a sequence:
# → create → draw → label → display

# ------------------------------------------------------------
# 13. Optional: Histogram version
# ------------------------------------------------------------
#
# This is another way to display the same simulation output.
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))
plt.hist(df_1000_sims["Total_Portfolio_Loss"], bins=15, edgecolor="black")

plt.xlabel("Total Portfolio Loss (EUR)")
plt.ylabel("Frequency")
plt.title("Histogram of Simulated Portfolio Losses")
plt.grid(axis="y", alpha=0.3)
plt.show()



# ------------------------------------------------------------
# 14. Interpretation
# ------------------------------------------------------------
#
# Key points:
#
# (1) Each firm's default is a random variable.
#     It is not known in advance whether default = 0 or 1.
#
# (2) The firm's loss is also a random variable,
#     because it depends on the random default event.
#
# (3) The total portfolio loss is a random variable made up of
#     the sum of the 10 firm-level losses.
#
# (4) Simulation means repeating the random experiment many times.
#     This helps us understand:
#         - average loss
#         - variability of loss
#         - how often large losses occur
#         - the overall loss distribution
#
# (5) The theoretical expected loss is the long-run average.
#     The simulated average loss should get closer to it when
#     the number of simulations increases.
# ------------------------------------------------------------